# Spending Classifier

### Objective is to train a model that will be able to classify my credit card purchases into 4 classes : Food, Entertainment, Gas, & Other

Classes are mapped to integers as follows: 

- Food : 1 
- Entertainment : 2 
- Gas : 3 
- Other : 4

In [101]:
import pandas as pd

In [102]:
df = pd.read_excel('spendingdata.xlsx')

# Clean Data

## Remove credit rows

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226 entries, 0 to 225
Data columns (total 11 columns):
Transaction Date       226 non-null datetime64[ns]
 Posting Date          226 non-null datetime64[ns]
 Billing Amount        226 non-null float64
 Merchant              226 non-null object
 Merchant City         217 non-null object
 Merchant State        210 non-null object
 Merchant Zip          210 non-null float64
 Reference Number      226 non-null object
 Debit/Credit Flag     226 non-null object
 SICMCC Code           226 non-null int64
Class                  226 non-null object
dtypes: datetime64[ns](2), float64(2), int64(1), object(6)
memory usage: 19.5+ KB

In [104]:
df = df.drop(df[df[' Debit/Credit Flag '] == 'C'].index)

In [105]:
df

,Transaction Date,Posting Date,Billing Amount,Merchant,Merchant City,Merchant State,Merchant Zip,Reference Number,Debit/Credit Flag,SICMCC Code,Class
1,2017-03-01,2017-03-02,35.76,CUMBERLAND FA 91187210,CHELMSFORD,MA,1824.0,"""24231687061837008824001""",D,5542,G
2,2017-02-28,2017-03-02,18.54,PRESSED CAFE,NASHUA,NH,3062.0,"""24692167060000888528350""",D,5814,F
3,2017-02-27,2017-03-01,10.64,CAFE SERVICES - THE TA,NASHUA,NH,3062.0,"""24269797059500575945460""",D,5814,F
4,2017-02-25,2017-02-27,28.00,SENMONOROM RESTAURANT,LOWELL,MA,1851.0,"""24055237056400058000347""",D,5812,F
5,2017-02-25,2017-02-27,115.17,WAMESIT LANES - BOWLIN,TEWKSBURY,MA,1876.0,"""24269797057100636824796""",D,7933,E
6,2017-02-25,2017-02-27,17.74,Dig Inn Season Market - B,New York,NY,10001.0,"""24342857057700086431357""",D,5812,F
7,2017-02-24,2017-02-27,8.76,MCDONALD'S F11790,LOWELL,MA,1851.0,"""24427337055720055111502""",D,5814,F
8,2017-02-23,2017-02-24,12.66,UNCHARTED GALLERY,Lowell,MA,1852.0,"""24828247054001347856155""",D,5812,E
9,2017-02-23,2017-02-27,10.28,CAFE SERVICES - THE TA,NASHUA,NH,3062.0,"""24269797055500621300706""",D,5814,F
10,2017-02-22,2017-02-24,19.63,PRESSED CAFE,NASHUA,NH,3062.0,"""24692167054000130707461""",D,5814,F
11,2017-02-21,2017-02-21,10.50,EGYPTIAN GRILL,LOWELL,MA,1854.0,"""24431067052091045000159""",D,5814,F
13,2017-02-21,2017-02-22,6.48,WALGREENS #11726,LOWELL,MA,1851.0,"""24445007053600209524405""",D,5912,O
14,2017-02-21,2017-02-23,14.45,PRESSED CAFE,NASHUA,NH,3062.0,"""24692167053000561166634""",D,5814,F
15,2017-02-21,2017-02-23,35.19,EXXONMOBIL 97535595,LOWELL,MA,1851.0,"""24164057053378012317937""",D,5542,G
16,2017-02-20,2017-02-21,68.84,WWW.ADVANCEAUTOPARTS,877-238-2623,VA,24012.0,"""24326887051083455803123""",D,5533,O
17,2017-02-20,2017-02-21,39.00,PHO 88 RESTAURANT INC,LOWELL,MA,1851.0,"""24275397052010288522067""",D,5812,F
18,2017-02-19,2017-02-20,75.00,PAYPAL *NEIVSA,402-935-7733,CA,95131.0,"""24492157050894773071517""",D,8398,E
19,2017-02-18,2017-02-20,11.16,CHIPOTLE ONLINE,3035954000,CO,80202.0,"""24431067049083702874543""",D,5814,F
20,2017-02-18,2017-02-20,15.00,SHOWCASE CINEMAS,LOWELL,MA,1851.0,"""24445007050000780015266""",D,7832,E
21,2017-02-18,2017-02-20,10.61,CVS/PHARMACY #01056,LOWELL,MA,1851.0,"""24445007050000780015183""",D,5912,O
22,2017-02-18,2017-02-20,4.00,0628 PLANET FITNESS,DRACUT,MA,1826.0,"""24910167050007184879690""",D,7997,O
23,2017-02-17,2017-02-20,55.74,BON CHON - LOWELL,LOWELL,MA,1851.0,"""24269797049500805302931""",D,5812,F
24,2017-02-16,2017-02-16,22.67,PHO DA LAT STORE #1,CHELMSFORD,MA,1824.0,"""24692167047000011031353""",D,5812,F
25,2017-02-16,2017-02-17,9.76,VALENTINO'S MARKET,NASHUA,NH,3062.0,"""24224437048103018785337""",D,5499,F
26,2017-02-15,2017-02-16,9.58,EAT24 *MAZA,EAT24HOURS.CO,CA,94105.0,"""24492157046637007392473""",D,5499,F
27,2017-02-14,2017-02-16,7.35,CAFE SERVICES - THE TA,NASHUA,NH,3062.0,"""24269797046500657627545""",D,5814,F
28,2017-02-13,2017-02-13,40.00,BOSTON PARKING TICKETS,617-635-4410,MA,2201.0,"""24692167044000258213105""",D,9399,E
29,2017-02-13,2017-02-13,1.10,ICI*FEE BOSTON WEB PMT,866-342-9267,MA,2184.0,"""24692167044000258220241""",D,9399,O
30,2017-02-13,2017-02-15,11.43,NOODLES & CO 7903,NASHUA,NH,3060.0,"""24431067045207288600352""",D,5812,F
31,2017-02-11,2017-02-13,29.46,PACE ENERGY,LOWELL,MA,1850.0,"""24765017043006000316146""",D,5542,G
...,...,...,...,...,...,...,...,...,...,...,...
196,2017-04-24,2017-04-25,18.53,PRESSED CAFE,NASHUA,NH,3063.0,"""24224437115105000616600""",D,5812,F
197,2017-04-23,2017-04-24,36.88,MARKET BASKET 00000190,LOWELL,MA,1851.0,"""24164077113433001007050""",D,5411,F
198,2017-04-21,2017-04-24,23.79,TAVERN IN THE SQUARE,LOWELL,MA,1851.0,"""24228997113018093145000""",D,5812,F
199,2017-04-20,2017-04-20,44.05,PHO DA LAT STORE #1,CHELMSFORD,MA,1824.0,"""24692167110000426439862""",D,5812,F
200,2017-04-20,2017-04-21,36.22,LUKOIL,TYNGSBORO,MA,1879.0,"""24055227110006004912777""",D,5542,G
201,2017-04-20,2017-04-21,24.24,CHINA STAR,LOWELL,MA,1851.0,"""24275397110010646609812""",D,5812,F
202,2017-04-20,2017-04-24,21.40,BGOOD NASHUA,NASHUA,NH,3060.0,"""24307927111900016600224""",D,5814,F
203,2017-04-19,2017-04-20,14.17,PRESSED CAFE,NASHUA,NH,3063.0,"""24224437110105000626612""",D,5812,F
204,2017-04-18,2017-04-20,10.16,CAFE SERVICES - THE TA,NASHUA,NH,3062.0,"""24269797109500600421784""",D,5814,F
205,2017-04-17,2017-04-18,14.46,5GUYS 1593 QSR,NASHUA,NH,3060.0,"""24445007107300429144623""",D,5814,F
206,2017-04-16,2017-04-18,28.00,RED ROSE RESTAURANT,LOWELL,MA,1851.0,"""24207857107204900675756""",D,5812,F
207,2017-04-15,2017-04-17,16.05,PRESSED CAFE,BURLINGTON,MA,1803.0,"""24224437106104009300549""",D,5812,F
208,2017-04-14,2017-04-17,104.94,MARSHALLS #0025,NASHUA,NH,3060.0,"""24445007105000967302219""",D,5651,O
209,2017-04-13,2017-04-17,12.36,CAFE SERVICES - THE TA,NASHUA,NH,3062.0,"""24269797104500705751833""",D,5814,F
210,2017-04-12,2017-04-13,55.25,AXS.COM*BOWERY PRSNTS,888-929-7849,CA,90015.0,"""24692167102000830421688""",D,7922,E
211,2017-04-12,2017-04-13,11.34,CHIPOTLE 1373,NASHUA,NH,3060.0,"""24431067103207888700387""",D,5814,F
212,2017-04-11,2017-04-12,11.45,PRESSED CAFE,NASHUA,NH,3063.0,"""24224437102105000640076""",D,5812,F
213,2017-04-10,2017-04-10,22.00,EGYPTIAN GRILL,LOWELL,MA,1854.0,"""24431067100091045000136""",D,5814,F
214,2017-04-10,2017-04-11,13.34,FANDANGO.COM,FANDANGO.COM,CA,90064.0,"""24692167100000486104945""",D,7832,E
215,2017-04-10,2017-04-11,11.86,NOODLES & CO 7903,NASHUA,NH,3060.0,"""24431067101207288600080""",D,5812,F
216,2017-04-09,2017-04-10,13.34,FANDANGO.COM,FANDANGO.COM,CA,90064.0,"""24692167099000926378417""",D,7832,E
217,2017-04-09,2017-04-10,29.12,SPEEDWAY 02468,LOWELL,MA,1854.0,"""24224437100101028750791""",D,5542,G
218,2017-04-09,2017-04-10,8.07,WALGREENS #11726,LOWELL,MA,1851.0,"""24445007100600131639555""",D,5912,O
219,2017-04-08,2017-04-10,99.99,FOOT LOCKER 07693,NASHUA,NH,3060.0,"""24717057099730998250805""",D,5661,O
220,2017-04-08,2017-04-10,5.44,TEAVANA #178,NASHUA,NH,3060.0,"""24692167099000960419689""",D,5499,F
221,2017-04-07,2017-04-10,8.18,PRESSED CAFE,NASHUA,NH,3063.0,"""24224437098105000975874""",D,5812,F
222,2017-04-06,2017-04-07,10.00,SQ *THE CHICKEN AND RICE,Burlington,MA,1803.0,"""24692167096000239603728""",D,5814,F
223,2017-04-06,2017-04-07,16.58,HONG CUC GRAND EATERY IN,LOWELL,MA,1851.0,"""24733097096400634000159""",D,5812,F
224,2017-04-06,2017-04-10,109.00,INSIGHT OPTICAL,BURLINGTON,MA,1803.0,"""24910167097007317679491""",D,8042,O
225,2017-04-04,2017-04-06,12.47,CAFE SERVICES - THE TA,NASHUA,NH,3062.0,"""24269797095500517898781""",D,5814,F

In [106]:
df.columns

Index(['Transaction Date', ' Posting Date', ' Billing Amount', ' Merchant',
       ' Merchant City ', ' Merchant State ', ' Merchant Zip ',
       ' Reference Number ', ' Debit/Credit Flag ', ' SICMCC Code', 'Class'],
      dtype='object')

### Strip whitespace from column names

In [107]:
df.columns = df.columns.str.strip()

### Delete  Unnecessary Columns

In [108]:
df = df.drop('Reference Number',1)

In [109]:
df = df.drop('SICMCC Code',1)

In [110]:
df = df.drop('Merchant Zip',1)

In [111]:
df = df.drop('Debit/Credit Flag',1)

In [112]:
df = df.drop('Posting Date',1)

In [113]:
df = df.drop('Merchant City',1)
df = df.drop('Merchant State',1)

In [114]:
df['Merchant']

1         CUMBERLAND FA 91187210
2                   PRESSED CAFE
3         CAFE SERVICES - THE TA
4          SENMONOROM RESTAURANT
5         WAMESIT LANES - BOWLIN
6      Dig Inn Season Market - B
7              MCDONALD'S F11790
8              UNCHARTED GALLERY
9         CAFE SERVICES - THE TA
10                  PRESSED CAFE
11                EGYPTIAN GRILL
13              WALGREENS #11726
14                  PRESSED CAFE
15        EXXONMOBIL    97535595
16          WWW.ADVANCEAUTOPARTS
17         PHO 88 RESTAURANT INC
18                PAYPAL *NEIVSA
19               CHIPOTLE ONLINE
20              SHOWCASE CINEMAS
21           CVS/PHARMACY #01056
22           0628 PLANET FITNESS
23             BON CHON - LOWELL
24           PHO DA LAT STORE #1
25            VALENTINO'S MARKET
26                   EAT24 *MAZA
27        CAFE SERVICES - THE TA
28        BOSTON PARKING TICKETS
29        ICI*FEE BOSTON WEB PMT
30             NOODLES & CO 7903
31                   PACE ENERGY
                 ...
196                 PRESSED CAFE
197       MARKET BASKET 00000190
198         TAVERN IN THE SQUARE
199          PHO DA LAT STORE #1
200                       LUKOIL
201                   CHINA STAR
202                 BGOOD NASHUA
203                 PRESSED CAFE
204       CAFE SERVICES - THE TA
205               5GUYS 1593 QSR
206          RED ROSE RESTAURANT
207                 PRESSED CAFE
208              MARSHALLS #0025
209       CAFE SERVICES - THE TA
210        AXS.COM*BOWERY PRSNTS
211                CHIPOTLE 1373
212                 PRESSED CAFE
213               EGYPTIAN GRILL
214                 FANDANGO.COM
215            NOODLES & CO 7903
216                 FANDANGO.COM
217               SPEEDWAY 02468
218             WALGREENS #11726
219            FOOT LOCKER 07693
220                 TEAVANA #178
221                 PRESSED CAFE
222     SQ *THE CHICKEN AND RICE
223     HONG CUC GRAND EATERY IN
224              INSIGHT OPTICAL
225       CAFE SERVICES - THE TA
Name: Merchant, Length: 216, dtype: object

### Clean Merchant Data

In [115]:
clean_data = df['Merchant'].str.strip()

In [116]:
import re

In [117]:
clean_data = df['Merchant'].map(lambda x: re.sub(r'[^a-zA-Z\s]','', x))

In [118]:
df['Merchant'] = clean_data

In [119]:
df

    Transaction Date  Billing Amount                  Merchant Class
1         2017-03-01           35.76            CUMBERLAND FA      G
2         2017-02-28           18.54              PRESSED CAFE     F
3         2017-02-27           10.64     CAFE SERVICES  THE TA     F
4         2017-02-25           28.00     SENMONOROM RESTAURANT     F
5         2017-02-25          115.17     WAMESIT LANES  BOWLIN     E
6         2017-02-25           17.74  Dig Inn Season Market  B     F
7         2017-02-24            8.76               MCDONALDS F     F
8         2017-02-23           12.66         UNCHARTED GALLERY     E
9         2017-02-23           10.28     CAFE SERVICES  THE TA     F
10        2017-02-22           19.63              PRESSED CAFE     F
11        2017-02-21           10.50            EGYPTIAN GRILL     F
13        2017-02-21            6.48                WALGREENS      O
14        2017-02-21           14.45              PRESSED CAFE     F
15        2017-02-21           35.19            EXXONMOBIL         G
16        2017-02-20           68.84       WWWADVANCEAUTOPARTS     O
17        2017-02-20           39.00       PHO  RESTAURANT INC     F
18        2017-02-19           75.00             PAYPAL NEIVSA     E
19        2017-02-18           11.16           CHIPOTLE ONLINE     F
20        2017-02-18           15.00          SHOWCASE CINEMAS     E
21        2017-02-18           10.61              CVSPHARMACY      O
22        2017-02-18            4.00            PLANET FITNESS     O
23        2017-02-17           55.74          BON CHON  LOWELL     F
24        2017-02-16           22.67         PHO DA LAT STORE      F
25        2017-02-16            9.76         VALENTINOS MARKET     F
26        2017-02-15            9.58                  EAT MAZA     F
27        2017-02-14            7.35     CAFE SERVICES  THE TA     F
28        2017-02-13           40.00    BOSTON PARKING TICKETS     E
29        2017-02-13            1.10     ICIFEE BOSTON WEB PMT     O
30        2017-02-13           11.43              NOODLES  CO      F
31        2017-02-11           29.46               PACE ENERGY     G
..               ...             ...                       ...   ...
196       2017-04-24           18.53              PRESSED CAFE     F
197       2017-04-23           36.88            MARKET BASKET      F
198       2017-04-21           23.79      TAVERN IN THE SQUARE     F
199       2017-04-20           44.05         PHO DA LAT STORE      F
200       2017-04-20           36.22                    LUKOIL     G
201       2017-04-20           24.24                CHINA STAR     F
202       2017-04-20           21.40              BGOOD NASHUA     F
203       2017-04-19           14.17              PRESSED CAFE     F
204       2017-04-18           10.16     CAFE SERVICES  THE TA     F
205       2017-04-17           14.46                 GUYS  QSR     F
206       2017-04-16           28.00       RED ROSE RESTAURANT     F
207       2017-04-15           16.05              PRESSED CAFE     F
208       2017-04-14          104.94                MARSHALLS      O
209       2017-04-13           12.36     CAFE SERVICES  THE TA     F
210       2017-04-12           55.25       AXSCOMBOWERY PRSNTS     E
211       2017-04-12           11.34                 CHIPOTLE      F
212       2017-04-11           11.45              PRESSED CAFE     F
213       2017-04-10           22.00            EGYPTIAN GRILL     F
214       2017-04-10           13.34               FANDANGOCOM     E
215       2017-04-10           11.86              NOODLES  CO      F
216       2017-04-09           13.34               FANDANGOCOM     E
217       2017-04-09           29.12                 SPEEDWAY      G
218       2017-04-09            8.07                WALGREENS      O
219       2017-04-08           99.99              FOOT LOCKER      O
220       2017-04-08            5.44                  TEAVANA      F
221       2017-04-07            8.18              PRESSED CAFE     F
222       2017-04-06           10.00   SQ THE CHICKEN AND RICE     F
223       2017-04-06           16.58  HONG CUC GRAND EATERY IN     F
224       2017-04-06          109.00           INSIGHT OPTICAL     O
225       2017-04-04           12.47     CAFE SERVICES  THE TA     F

[216 rows x 4 columns]

### Convert Class to Integer

In [120]:
def convert(s):
    class_map = {'F':1,'E':2,'G':3,'O':4}
    if s in class_map:
        return class_map[s]
    else:
        return 'O'

In [121]:
converted_class = df['Class'].map(convert)

In [122]:
df['Class'] = converted_class


### Feature Extraction, Bag of Words Bi-gram

In [123]:
from sklearn.feature_extraction.text import CountVectorizer

In [124]:
# list of words that we want to exclude from vocabulary 
exclude_words =['the','llc','and']
# Only include words that have atleast 3 characters into our vocabulary 
bigram_vectorizer = CountVectorizer(ngram_range=(1, 2),
                                     token_pattern=r'\b\w{3,}\b', min_df=1, stop_words=exclude_words)

In [125]:
counts = bigram_vectorizer.fit_transform(df['Merchant'])

In [126]:
counts

<216x298 sparse matrix of type '<class 'numpy.int64'>'
	with 644 stored elements in Compressed Sparse Row format>

In [127]:
counts.toarray().astype(int)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [128]:
names = bigram_vectorizer.get_feature_names()

names

In [129]:
names

['alewife',
 'amazon',
 'amazon mktplace',
 'amazoncom',
 'angelinas',
 'angelinas pizzeria',
 'apple',
 'apple store',
 'aramark',
 'aramark umass',
 'aramark uml',
 'auto',
 'auto body',
 'axscombowery',
 'axscombowery prsnts',
 'bamboo',
 'bar',
 'bar salem',
 'barbershop',
 'basket',
 'bath',
 'bath body',
 'bgood',
 'bgood nashua',
 'bistro',
 'bit',
 'bit bar',
 'body',
 'body works',
 'bon',
 'bon chon',
 'boston',
 'boston common',
 'boston parking',
 'boston web',
 'boston yummy',
 'bostonwoburn',
 'bowlin',
 'bread',
 'brook',
 'brook market',
 'brunswick',
 'brunswick zone',
 'burlington',
 'cafe',
 'cafe services',
 'care',
 'care success',
 'castles',
 'chargefee',
 'chargepurchases',
 'cheesecake',
 'cheesecake burlington',
 'chicken',
 'chicken rice',
 'chilis',
 'chilis lowell',
 'china',
 'china pearl',
 'china star',
 'chipotle',
 'chipotle online',
 'chon',
 'chon lowell',
 'cinemas',
 'cinemas lowell',
 'comics',
 'common',
 'common frog',
 'copley',
 'cuc',
 'cuc grand',
 'cumberland',
 'cvspharmacy',
 'dicks',
 'dicks sporting',
 'dig',
 'dig inn',
 'dollar',
 'dominos',
 'dunkin',
 'eat',
 'eat maza',
 'eatery',
 'egyptian',
 'egyptian grill',
 'eleven',
 'embed',
 'energy',
 'ever',
 'ever chicken',
 'exxonmobil',
 'family',
 'family dollar',
 'fandangocom',
 'fee',
 'fitness',
 'foot',
 'foot locker',
 'foster',
 'foster care',
 'frog',
 'frog pond',
 'frozen',
 'fusion',
 'fusion presents',
 'gainsborough',
 'gainsborough garage',
 'gallery',
 'garage',
 'garden',
 'ginos',
 'goods',
 'google',
 'google services',
 'grand',
 'grand eatery',
 'grill',
 'gulf',
 'gulf oil',
 'guys',
 'guys qsr',
 'hilton',
 'hilton bostonwoburn',
 'hong',
 'hong cuc',
 'ice',
 'ice castles',
 'icifee',
 'icifee boston',
 'inc',
 'inn',
 'inn season',
 'insight',
 'insight optical',
 'interest',
 'interest chargefee',
 'interest chargepurchases',
 'its',
 'its wrap',
 'japanese',
 'jeon',
 'lanes',
 'lanes bowlin',
 'lanes embed',
 'lat',
 'lat store',
 'late',
 'late payment',
 'leaf',
 'leaf frozen',
 'locker',
 'lowell',
 'lowell onstreet',
 'lowell star',
 'lukoil',
 'maki',
 'maki japanese',
 'maki maki',
 'market',
 'market basket',
 'market street',
 'marketplace',
 'marshalls',
 'maza',
 'mbta',
 'mbta alewife',
 'mbta copley',
 'mcdonalds',
 'merrimack',
 'merrimack rep',
 'mktplace',
 'mktplace pmts',
 'nashua',
 'nayax',
 'neivsa',
 'newbury',
 'newbury comics',
 'noodles',
 'oil',
 'olive',
 'olive garden',
 'online',
 'onstreet',
 'optical',
 'orange',
 'orange leaf',
 'ouk',
 'pace',
 'pace energy',
 'pacsun',
 'panera',
 'panera bread',
 'papa',
 'papa ginos',
 'parking',
 'parking tickets',
 'payment',
 'payment fee',
 'paypal',
 'paypal neivsa',
 'pearl',
 'pearl restaurant',
 'pho',
 'pho ever',
 'pho lat',
 'pho restaurant',
 'pizzeria',
 'planet',
 'planet fitness',
 'pmt',
 'pmts',
 'pond',
 'powers',
 'powers wine',
 'presents',
 'pressed',
 'pressed cafe',
 'prsnts',
 'purple',
 'purple bamboo',
 'qsr',
 'ramen',
 'ramen bar',
 'red',
 'red rose',
 'rep',
 'rep thtr',
 'restaurant',
 'restaurant inc',
 'rice',
 'rmv',
 'rmv web',
 'rose',
 'rose restaurant',
 'rps',
 'rps lowell',
 'salem',
 'season',
 'season market',
 'senmonorom',
 'senmonorom restaurant',
 'services',
 'showcase',
 'showcase cinemas',
 'snowdaes',
 'speedway',
 'spit',
 'spit brook',
 'sporting',
 'sporting goods',
 'square',
 'star',
 'stay',
 'stay true',
 'store',
 'street',
 'street market',
 'success',
 'target',
 'tavern',
 'tavern square',
 'tea',
 'teavana',
 'thtr',
 'tickets',
 'transaction',
 'true',
 'true barbershop',
 'tst',
 'tst bit',
 'umass',
 'umass lowell',
 'uml',
 'uml marketplace',
 'uncharted',
 'uncharted gallery',
 'valentinos',
 'valentinos market',
 'vmk',
 'walgreens',
 'wamesit',
 'wamesit lanes',
 'wayfairwayfair',
 'web',
 'web pmt',
 'web transaction',
 'wendys',
 'wine',
 'woo',
 'woo jeon',
 'works',
 'wpybunnath',
 'wpybunnath ouk',
 'wrap',
 'wwwadvanceautoparts',
 'yummy',
 'zone']

In [130]:
print (counts.shape)

(216, 298)

In [131]:
print (counts[0])

  (0, 72)	1

In [132]:
print (names[84])
print (names[113])
print (names[83])

egyptian
google
eatery

Counts contains is a numpy array that has num of occurences for each word in the vocab for each row, this is our data set that needs to be split and trained.

In [133]:
import numpy as np

In [134]:
train_counts = counts[:150]

In [135]:
test_counts = counts[150:]

In [136]:
# The class label we are predicting 
train_target = df['Class'][:150]

In [137]:
test_target = df['Class'][150:]

### Data has been split 70% train & 30% test

In [138]:
### Train model using random forest

In [139]:
from sklearn.ensemble import RandomForestClassifier

# Initialize a Random Forest classifier with 100 trees
forest = RandomForestClassifier(n_estimators = 100) 

# Fit the forest to the training set, using the bag of words as 
# features and the sentiment labels as the response variable
#
# This may take a few minutes to run
forest = forest.fit( train_counts, train_target)

In [140]:
train_counts_predict = forest.predict(train_counts)

In [141]:
from sklearn import metrics

In [142]:
print ("Accuracy: {0:.4f}".format(metrics.accuracy_score(train_target,train_counts_predict)))

Accuracy: 1.0000

In [143]:
test_counts_predict = forest.predict(test_counts)

In [144]:
print ("Accuracy: {0:.4f}".format(metrics.accuracy_score(test_target,test_counts_predict)))

Accuracy: 0.8333

In [145]:
test_counts_predict

array([4, 1, 1, 3, 1, 1, 2, 2, 4, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 4, 4, 4,
       1, 4, 1, 4, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 4, 1, 1, 1, 1, 1, 1, 1])

In [146]:
result = zip(df['Merchant'][150:],test_counts_predict)

In [147]:
def numToClass(num):
    class_map = {1:'Food',2:"Entertainment",3:"Gas",4:'Other'}
    return class_map[num]

for merchant, prediction in result:
    print(merchant, numToClass(prediction))

RPS OF LOWELL ONSTREET ME Other
EGYPTIAN GRILL Food
ANGELINAS PIZZERIA AND SU Food
SPEEDWAY  Gas
MARKET BASKET  Food
SENMONOROM RESTAURANT Food
SHOWCASE CINEMAS Entertainment
SHOWCASE CINEMAS LOWELL Entertainment
RPS OF LOWELL ONSTREET ME Other
DUNKIN      Q Food
WENDYS  Food
DOMINOS  Food
EGYPTIAN GRILL Food
CHIPOTLE  Food
RPS OF LOWELL ONSTREET ME Other
NAYAX LLC  Food
BOSTON YUMMY LLC Food
GAINSBOROUGH GARAGE Food
BON CHON  LOWELL Food
BON CHON  LOWELL Food
INTEREST CHARGEPURCHASES Other
INTEREST CHARGEFEE Other
LATE PAYMENT FEE Other
CHIPOTLE  Food
TARGET         Other
EGYPTIAN GRILL Food
CVSPHARMACY  Other
GULF OIL  Gas
DUNKIN      Q Food
CAFE SERVICES  THE TA Food
CAFE SERVICES  THE TA Food
CAFE SERVICES  THE TA Food
CAFE SERVICES  THE TA Food
  BRUNSWICK ZONE  Food
  BRUNSWICK ZONE  Food
SPIT BROOK MARKET Food
PRESSED CAFE Food
MARKET BASKET  Food
TAVERN IN THE SQUARE Food
PHO DA LAT STORE  Food
LUKOIL Food
CHINA STAR Food
BGOOD NASHUA Food
PRESSED CAFE Food
CAFE SERVICES  THE TA Food
GUYS  QSR Food
RED ROSE RESTAURANT Food
PRESSED CAFE Food
MARSHALLS  Food
CAFE SERVICES  THE TA Food
AXSCOMBOWERY PRSNTS Food
CHIPOTLE  Food
PRESSED CAFE Food
EGYPTIAN GRILL Food
FANDANGOCOM Food
NOODLES  CO  Food
FANDANGOCOM Food
SPEEDWAY  Gas
WALGREENS  Other
FOOT LOCKER  Food
TEAVANA  Food
PRESSED CAFE Food
SQ THE CHICKEN AND RICE Food
HONG CUC GRAND EATERY IN Food
INSIGHT OPTICAL Food
CAFE SERVICES  THE TA Food

In [148]:
df[df['Class'] == 1]

    Transaction Date  Billing Amount                   Merchant  Class
2         2017-02-28           18.54               PRESSED CAFE      1
3         2017-02-27           10.64      CAFE SERVICES  THE TA      1
4         2017-02-25           28.00      SENMONOROM RESTAURANT      1
6         2017-02-25           17.74   Dig Inn Season Market  B      1
7         2017-02-24            8.76                MCDONALDS F      1
9         2017-02-23           10.28      CAFE SERVICES  THE TA      1
10        2017-02-22           19.63               PRESSED CAFE      1
11        2017-02-21           10.50             EGYPTIAN GRILL      1
14        2017-02-21           14.45               PRESSED CAFE      1
17        2017-02-20           39.00        PHO  RESTAURANT INC      1
19        2017-02-18           11.16            CHIPOTLE ONLINE      1
23        2017-02-17           55.74           BON CHON  LOWELL      1
24        2017-02-16           22.67          PHO DA LAT STORE       1
25        2017-02-16            9.76          VALENTINOS MARKET      1
26        2017-02-15            9.58                   EAT MAZA      1
27        2017-02-14            7.35      CAFE SERVICES  THE TA      1
30        2017-02-13           11.43               NOODLES  CO       1
32        2017-02-11            3.75                     TEA DO      1
33        2017-02-10           17.45               PRESSED CAFE      1
36        2017-04-03           13.63               PRESSED CAFE      1
37        2017-04-02            9.61                MCDONALDS F      1
38        2017-04-02           44.18             MARKET BASKET       1
39        2017-04-02           41.22              PURPLE BAMBOO      1
42        2017-03-31           11.18                  CHIPOTLE       1
43        2017-03-31           11.45               PRESSED CAFE      1
44        2017-03-30           12.44      CAFE SERVICES  THE TA      1
45        2017-03-30            4.85  ARAMARK UMASS LOWELL STAR      1
46        2017-03-29            9.78      CAFE SERVICES  THE TA      1
48        2017-03-28           12.26               PRESSED CAFE      1
49        2017-03-27            8.97      CAFE SERVICES  THE TA      1
..               ...             ...                        ...    ...
178       2016-11-04           16.75           BON CHON  LOWELL      1
183       2017-05-01           10.85                  CHIPOTLE       1
185       2017-04-29           10.50             EGYPTIAN GRILL      1
188       2017-04-28            7.24              DUNKIN      Q      1
189       2017-04-27            9.99      CAFE SERVICES  THE TA      1
190       2017-04-26            7.65      CAFE SERVICES  THE TA      1
191       2017-04-26            3.25      CAFE SERVICES  THE TA      1
192       2017-04-25            1.69      CAFE SERVICES  THE TA      1
195       2017-04-24            2.00          SPIT BROOK MARKET      1
196       2017-04-24           18.53               PRESSED CAFE      1
197       2017-04-23           36.88             MARKET BASKET       1
198       2017-04-21           23.79       TAVERN IN THE SQUARE      1
199       2017-04-20           44.05          PHO DA LAT STORE       1
201       2017-04-20           24.24                 CHINA STAR      1
202       2017-04-20           21.40               BGOOD NASHUA      1
203       2017-04-19           14.17               PRESSED CAFE      1
204       2017-04-18           10.16      CAFE SERVICES  THE TA      1
205       2017-04-17           14.46                  GUYS  QSR      1
206       2017-04-16           28.00        RED ROSE RESTAURANT      1
207       2017-04-15           16.05               PRESSED CAFE      1
209       2017-04-13           12.36      CAFE SERVICES  THE TA      1
211       2017-04-12           11.34                  CHIPOTLE       1
212       2017-04-11           11.45               PRESSED CAFE      1
213       2017-04-10           22.00             EGYPTIAN GRILL      1
215       2017-04-10           11.86               NOODLES  CO       1
220       2017-04-08            5.44                   TEAVANA       1
221       2017-04-07            8.18               PRESSED CAFE      1
222       2017-04-06           10.00    SQ THE CHICKEN AND RICE      1
223       2017-04-06           16.58   HONG CUC GRAND EATERY IN      1
225       2017-04-04           12.47      CAFE SERVICES  THE TA      1

[120 rows x 4 columns]